import React from 'react'
import { Form } from '../../index'

export default {
  title: 'ReactFormio/TextArea',
  component: Form,
  argTypes: {},
  parameters: {
    docs: {
      source: {
        type: 'code'
      }
    }
  }
}

export const Sandbox = (args) => {
  return (
    <Form form={args.form} options={args.options}/>
  )
}

Sandbox.args = {
  form: {
    '_id': '6023f8fe4b1a2ab9a3aae096',
    'type': 'form',
    'tags': [],
    'owner': '5d0797a382461b6656d2c790',
    'components': [{
      'label': 'Text Area',
      'labelPosition': 'top',
      'placeholder': 'Placeholder',
      'description': 'description',
      'tooltip': 'tooltip',
      'prefix': '',
      'suffix': '',
      'widget': { 'type': 'input' },
      'editor': '',
      'autoExpand': false,
      'customClass': '',
      'tabindex': '',
      'autocomplete': '',
      'hidden': false,
      'hideLabel': false,
      'showWordCount': false,
      'showCharCount': false,
      'autofocus': false,
      'spellcheck': true,
      'disabled': false,
      'tableView': true,
      'modalEdit': false,
      'multiple': false,
      'persistent': true,
      'inputFormat': 'html',
      'protected': false,
      'dbIndex': false,
      'case': '',
      'encrypted': false,
      'redrawOn': '',
      'clearOnHide': true,
      'customDefaultValue': '',
      'calculateValue': '',
      'calculateServer': false,
      'allowCalculateOverride': false,
      'validateOn': 'change',
      'validate': {
        'required': false,
        'pattern': '',
        'customMessage': '',
        'custom': '',
        'customPrivate': false,
        'json': '',
        'minLength': '',
        'maxLength': '',
        'minWords': '',
        'maxWords': '',
        'strictDateValidation': false,
        'multiple': false,
        'unique': false
      },
      'unique': false,
      'errorLabel': '',
      'key': 'textArea',
      'tags': [],
      'properties': {},
      'conditional': { 'show': null, 'when': null, 'eq': '', 'json': '' },
      'customConditional': '',
      'logic': [],
      'fixedSize': true,
      'overlay': { 'style': '', 'page': '', 'left': '', 'top': '', 'width': '', 'height': '' },
      'attributes': {},
      'type': 'textarea',
      'rows': 3,
      'wysiwyg': false,
      'input': true,
      'refreshOn': '',
      'allowMultipleMasks': false,
      'mask': false,
      'inputType': 'text',
      'inputMask': '',
      'id': 'e4jsrqc',
      'defaultValue': ''
    }, {
      'type': 'button',
      'label': 'Submit',
      'key': 'submit',
      'size': 'md',
      'block': false,
      'action': 'submit',
      'disableOnInvalid': true,
      'theme': 'primary',
      'input': true,
      'placeholder': '',
      'prefix': '',
      'customClass': '',
      'suffix': '',
      'multiple': false,
      'defaultValue': null,
      'protected': false,
      'unique': false,
      'persistent': false,
      'hidden': false,
      'clearOnHide': true,
      'refreshOn': '',
      'redrawOn': '',
      'tableView': false,
      'modalEdit': false,
      'labelPosition': 'top',
      'description': '',
      'errorLabel': '',
      'tooltip': '',
      'hideLabel': false,
      'tabindex': '',
      'disabled': false,
      'autofocus': false,
      'dbIndex': false,
      'customDefaultValue': '',
      'calculateValue': '',
      'calculateServer': false,
      'widget': { 'type': 'input' },
      'attributes': {},
      'validateOn': 'change',
      'validate': {
        'required': false,
        'custom': '',
        'customPrivate': false,
        'strictDateValidation': false,
        'multiple': false,
        'unique': false
      },
      'conditional': { 'show': null, 'when': null, 'eq': '' },
      'overlay': { 'style': '', 'left': '', 'top': '', 'width': '', 'height': '' },
      'allowCalculateOverride': false,
      'encrypted': false,
      'showCharCount': false,
      'showWordCount': false,
      'properties': {},
      'allowMultipleMasks': false,
      'leftIcon': '',
      'rightIcon': '',
      'dataGridLabel': true,
      'id': 'e08gq3l'
    }],
    'revisions': '',
    '_vid': 0,
    'title': 'text-field',
    'display': 'form',
    'access': [{
      'roles': ['5d0797bc872fc747da559858', '5d0797bc872fc71d05559859', '5d0797bc872fc7da3b55985a'],
      'type': 'read_all'
    }],
    'submissionAccess': [],
    'controller': '',
    'properties': {},
    'settings': {},
    'name': 'textField',
    'path': 'textfield',
    'project': '5d0797bc872fc7d140559857',
    'created': '2021-02-10T15:17:18.028Z',
    'modified': '2021-02-10T19:27:04.340Z',
    'machineName': 'tcspjwhsevrzpcd:textField'
  },
  options: { template: 'bootstrap', iconset: 'fa' }
}
